---
output: github_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo=TRUE, collapse=TRUE)
```


```{r}
suppressPackageStartupMessages(library(tidyverse))
library(nycflights13)
```


## 5.6 summarise


```{r}
library(nycflights13)
library(tidyverse)
glimpse(flights)
```



```{r}
df <- flights %>%
	summarise(delay = mean(dep_delay, na.rm = TRUE))
glimpse(df)
```


`summarise()` is not terribly useful unless we pair it with `group_by()`


```{r}
this_group <- group_by(flights, year, month, day)
df <- summarise(this_group
								, delay = mean(dep_delay, na.rm = TRUE)
								, count = n()
								)

glimpse(df)

```


```{r}
delays <- flights %>% 
  group_by(dest) %>% 
  summarise(
    count = n(),
    dist = mean(distance, na.rm = TRUE),
    delay = mean(arr_delay, na.rm = TRUE)
  ) %>% 
	ungroup() %>%
  filter(count > 20, dest != "HNL")
```





```{r}
ggplot(data = delays, mapping = aes(x = dist, y = delay)) +
  geom_point(aes(size = count), alpha = 1/3) +
  geom_smooth(se = FALSE)
```


```{r}

```

