---
output: github_document
---

# setup git and github

## all graded work is pushed to GitHub  

Git is version control software you install on your machine. GitHub is a hosting service that provides an online home for your Git-based projects---critically important for sharing with collaborators. 

- [Why Git?](http://happygitwithr.com/big-picture.html#big-picture) Please read. 

Getting it all going may be a little painful, but after the first couple of weeks, using Git and GitHub will become second nature.  


## setup git and github  

[Jenny Bryan](https://github.com/jennybc) provided these instructions for a workshop I attended last June. She estimates that the setup work will take you 1--2 hours. 

Follow the instructions slowly and deliberately. 

There are a few instructions that ask you to type commands in the "shell". To access the shell, open RStudio and use the pulldown menu *Tools > Shell*. 
 

- [Register a free GitHub account](http://happygitwithr.com/github-acct.html#github-acct)  
- [Install Git locally](http://happygitwithr.com/install-git.html#install-git) 
- [Introduce yourself to Git](http://happygitwithr.com/hello-git.html#hello-git) 
- [Cache your username and password](http://happygitwithr.com/credential-caching.html#credential-caching) or  so you don’t need to authenticate yourself to GitHub interactively ad nauseum. Alternatively, you can [set up SSH keys](http://happygitwithr.com/ssh-keys.html#ssh-keys).  
- [Prove RStudio can find local Git](http://happygitwithr.com/rstudio-git-github.html#rstudio-git-github) and, therefore, can talk to GitHub 

---


[main page](../README.md)
