---
output: github_document
---


# getting help

ME497 Reproducible Research

## links I use regularly  

- [Quick R](http://www.statmethods.net/) for everyday R tasks  
- [R Markdown](http://rmarkdown.rstudio.com/) for syntax help  
- [knitr options](http://yihui.name/knitr/options/) 
- [R-bloggers](https://www.r-bloggers.com/), a searchable collection of R blog posts. 
- [Stackoverflow](http://stackoverflow.com/questions/tagged/r), a searchable Q&A website for programming questions. 
- [Advanced R](http://adv-r.had.co.nz/), when you really want to understand R
- [ggplot2 help](http://docs.ggplot2.org/current/index.html) for all of the details 

## books I recommend

- [*R in Action, 2/e*](https://www.manning.com/books/r-in-action-second-edition) by Robert Kabacoff, 2015, Manning Publications. If you want to buy just one good reference for R, this is the one I recommend. It covers R basics including statistical analysis and graphics. 
- [*R Graphics, 2/e*](https://www.crcpress.com/R-Graphics-Second-Edition/Murrell/p/book/9781439831762) by Paul Murrell, 2011, CRC Press. This is the book for learning about the four major R graphics systems (`base, grid, lattice, ggplot2`).  The author's [book website](https://www.stat.auckland.ac.nz/~paul/RG2e/) has the code for every figure in the book. 


---

[main page](../README.md)
