---
output: github_document
--- 

# wrap up project 2

The two summaries described below give me a quick summary of the review process. 

- For example, Carlos might say that he successfully reproduced Alice's work and  that all scripts compiled correctly. 
- Or Carlos may have found things that didn't work and so he summarizes what they are and what suggestion he may have had to fix the problems. 
- In response, Alice summarizes what she did to implement Carlos' suggestions, whether she was successful or not, and what future work should to be done to make the project fully reproducible. 

In any event, I know what to expect when I try to reproduce the scripts locally on my machine and I know what trouble spots each of you encountered, helping me customize future tutorials to enhance the prospect of success in the next project. 


## action items 

```{r 017-01, include = FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = TRUE)
options(echo = FALSE) # turns off echo in the console
```

Carlos (the reviewer) 

- PULL Alice's project one last time. 
- Open its README file. 
- Add a summary of the highlights of your review of the project. Write your review whether or not Alice has finished. 
- Save, Stage, Commit, Pull, Push. 
- Due by end-of-business Friday, week 6. 

Alice (the authors) 

- Carlos' summary is due by end-of-business Friday week 6. 
- Afterwards, PULL your project. 
- Open the README file. 
- In response to the reviewer's summary, summarize your own work that you did  in response to their suggestions. 
- Save, Stage, Commit, Pull, Push. (Don't forget the final PUSH or I won't be able to PULL your final version.) 




---

[main page](../README.md)




