---
output: github_document
---

# setup github


GitHub is a hosting service that provides an online home for your Git-based projects---critically important for sharing with collaborators. Once you have a GitHub account, you will update your repositories using the RStudio interface. 

- [What is GitHub?](../resources/readings/2017-Bryan-Version-control) Read section 4 for a good introduction to GitHub repositories 

## obtain an account

- [Join GitHub Education](http://happygitwithr.com/github-acct.html#free-private-repos) Follow the links to join GitHub Education --- it's free.  

## setup

Jenny Bryan provided the instructions below for a workshop I attended. I suggest you read the full instructions for one of the steps before doing that step. 

Some instructions ask you to type commands in the "shell". To access the shell, open RStudio and use the pulldown menu *Tools > Shell*.

- [Introduce yourself to Git](http://happygitwithr.com/hello-git.html#hello-git) using the name and  email you used with your GitHub account 
- [Cache your username and password](http://happygitwithr.com/credential-caching.html#credential-caching) or  so you don't need to authenticate yourself to GitHub interactively ad nauseum. Alternatively, you can [set up SSH keys](http://happygitwithr.com/ssh-keys.html#ssh-keys).  
- [Prove RStudio can find local Git](http://happygitwithr.com/rstudio-git-github.html#rstudio-git-github) and, therefore, can talk to GitHub 

## clean up

Once everything is working OK, you may delete any temporary test repos you made. 

- Delete the local test project directories 
- Navigate to the repo on GitHub and go to *Settings > Danger Zone > Delete this repository*

---

[main page](../README.md)
