---
output: github_document
bibliography: "../scripts/references-rr.bib"
csl: "../scripts/jpr.csl"
---

# setup directories 

## prerequisites 

You should have already created these R projects with version control and initialized them with README and gitignore files 

- practice work 
- project 1 
- project 2 
- project 3 (597 students only) 




## create a directory structure

All we are going to do is create a set of empty sub-directories (folders). 

- First, open one of your R projects 

Next, use one of these two approaches  

- In your OS, use your usual method for creating folders manually 
- In RStudio, find  *Files* in the pane ribbon and select *New Folder* 

Using either approach, create new folders for `data`, `manage`, etc. When done, the directory tree should look like this (you might have additional files such as `.gitignore` or `README.md`)

    project_folder/
        |-- data/
        |-- manage/
        |-- reports/
        |-- resources/
        |-- results/
        |-- scripts/
        |-- .Renviron
        `-- project_name.Rproj


## repeat 

Create the same directory structure for all of your projects. 

- practice_work 
- project 1 
- project 2 
- project 3 (597 students only) 



