---
output: github_document
bibliography: "../resources/bib-etc/references-rr.bib"
csl: "../resources/styles/jpr.csl"
link-citations: yes
--- 

```{r include = FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
```

# install R and RStudio 

## windows

- If you are a student or faculty member whose computer is maintained by an IT department, you will probably have a localmgr login account on your computer. If you do, you will have to login as the localmgr to install R and RStudio---it's not sufficient to have admin privileges on your usual login username. You must use localmgr. 

- If your computer is NOT maintained by an IT department, you can ignore the localmgr and just login in the usual way. 

- From the Comprehensive R Archive Network  [(CRAN)](http://cran.us.r-project.org/) download the latest version of _R for Windows_. Look for the link labeled _Install R for the very first time_. 

- Install the software in _C:/Program Files_. Accept all defaults. 

- Stay logged in as localmgr. 

- From [RStudio](http://www.rstudio.com/) &gt; Products &gt; RStudio &gt; Desktop &gt; Download RStudio Desktop &gt; and select Windows 

- Install the software in  _C:/Program Files_. Accept all defaults. 

- logout/signout of localmgr. 

If you followed these instructions carefully and encountered a problem, please let me know at <layton@rose-hulman.edu>.  The sooner we can fix the instructions, the fewer problems other students will encounter. 


## mac os

I'm not a MacOS user so I can only report to you what I have found online. 

- I would first just follow the instructions on [CRAN](https://cran.r-project.org/). 
- If you have any difficulty, you might try [Install R and RStudio on Mac](https://medium.com/@GalarnykMichael/install-r-and-rstudio-on-mac-e911606ce4f4) by Michael Galarnyk or google more recent instructions 


## linux os 

I'm not a Linux user so I can only report to you what I have found online. 

- I would first just follow the instructions on [CRAN](https://cran.r-project.org/). 
- If you have any difficulty, you might try [How to Install R Ubuntu 16.04 Xenial](http://www.datascienceriot.com//r/install-ubuntu16/)  by Kris Eberwein or google for recent instructions  





### shortcuts on the desktop

RStudio is an integrated development environment (IDE) for R, so I rarely run R directly. For this reason, I suggest

-   Put a shortcut to RStudio on the desktop 

-   Delete the shortcuts to R (if any) on your desktop  

