---
output: github_document
bibliography: "../resources/bib-etc/references-rr.bib"
csl: "../resources/styles/journal-of-simulation.csl"
---

```{r include=FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
library(tidyverse)
```


# commit to a repo

Before attempting the assignment, please read the lecture nites on [collaboration  basics](cm5005_how-to-collab.md).  


## activities 

Open one of your projects  

- Select the *Git* tab 


If there are files shown in the Git pane, 

- Click your cursor in the *git* pane 
- Select all the files using the keyboard shortcut *Ctrl A* (*Command A* in the Mac OS) 
- Stage all files by clicking in one of the *Staged* boxes 
- Select *Commit* 
- In the text box, write a short but descriptive message that summarizes the nature of the commit 
- *Commit* 
- *Pull* and you will see the message *Current branch master is up to date* (assuming Carlos has not yet made any changes) 
- *Close* 
- *Push* 
- *Close* 

Navigate to your online repo and you should find that it includes all your changes. 

- Repeat for all your projects. 


