---
output: github_document
bibliography: "../scripts/references-rr.bib"
csl: "../scripts/jpr.csl"
---

```{r include=FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
```

# controlling Word styles 

As you've seen, you can work reproducibly with Rmd scripts to produce documents in docx format. Often, this is the only format acceptable to your collaborators. 

What we haven't looked at yet is how to use Word styles reproducibly for  *document design.* 


## getting started

The basics of controlling Word styles  

- [Happy collaboration with Rmd to docx](http://rmarkdown.rstudio.com/articles_docx.html) 

## tips and tricks 

Later, you may find these useful  

- [R Markdown: How to insert page breaks in a MS Word document](http://datascienceplus.com/r-markdown-how-to-insert-page-breaks-in-a-ms-word-document/), how to format a style to produce a page break.  
- [Centering figures and captions](cm042_docx-center-figure.md) 
- [Math in R Markdown](http://www.stat.cmu.edu/~cshalizi/rmarkdown/#math-in-r-markdown) An excellent introduction to writing mathematics in Rmd. 
- [Using R Markdown for class reports](http://www.stat.cmu.edu/~cshalizi/rmarkdown/) Lots of good tips (including the math link above). 

If you find additional methods, or develop tricks of your own, let me know and I'll add them to the list. 

