---
output: github_document
--- 

# starting project 1


```{r, include = FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = TRUE)
options(echo = FALSE) # turns off echo in the console
```

Select a technical report from your past work in any course

- Start looking through your archives from earlier courses for a report you  (or a team of which you were a member) wrote dealing with data, analysis, and reporting (something like the sample calibration report)  
- Find two or three reports you think might be suitable 
- Print a hard copy of each report 

The reports should include most of these features

- Imports an image  
- Includes quantitative data that is used in some analysis to produce results 
- Includes a data table 
- Includes a graph to display quantitative results from the analysis 
- Show "in-line" results in the text of the report 
- Includes equation(s) 
- Citations and references 

## proposal 1 

- Bring the reports to class per the calendar. 
- I'll review the submissions and assign one to each student. 

<!-- ## what happens next  -->

<!-- - Create a project repo on GitHub and invite me to be a collaborator -->
<!-- - Initialize an RStudio Project for project 3 -->
<!-- - Start an R Markdown file and begin typing the report prose  -->






<!-- *No later than class day 3* -->

<!-- - Meet with me outside of class by appointment to discuss your proposed project and its general scope of work  -->

<!-- *No later than class day 6* -->


<!-- - Write a project proposal using R Markdown  ([guidelines](https://pressbooks.bccampus.ca/technicalwriting/chapter/7-1/))  -->
<!-- - Describe the specific type of data, analysis, and results you expect to produce for the week 6 progress report -->
<!-- - Describe the specific type of data, analysis, and results you expect to produce for the week 10 final report  -->
<!-- - Save any reference articles (typically PDFs) in the project `resources` directory  -->
<!-- - Stage, commit, and push your work to the repo  -->

<!-- As your collaborator, I can clone the project to my local machine, make comments directly in your files, and push to GitHub. You can then pull from GitHub, and open the files or knit them to see my comments.  -->





---

[main page](../README.md)




