---
output: github_document
--- 

# starting project 3


```{r 017-01, include = FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = TRUE)
options(echo = FALSE) # turns off echo in the console
```

ME 597 students only 


- Project 3 is the extra work you do in addition to the regular class work to satisfy the requirements of a 500-level course  
- Project 3 is reproducible research that should contribute to your thesis/project work  
- The work should include data, analysis, graphical results 
- Replication of prior work relevant to your thesis is often an appropriate goal 


## milestones 

- By the end of week 1, you and I will have agreed upon a basic framework of the project 
- By week 6, you will have made substantial progress on your project 
- Students who have not met expectations by week 6 will be switched from ME 597 to ME 497 
- By week 10, project 3 is complete and meets the expectations we have set 

## assignment 

*No later than class day 3*

- Meet with me outside of class by appointment to discuss your proposed project and its general scope of work 

*No later than class day 6*

- Create a project repo on GitHub and invite me to be a collaborator 
- Initialize an RStudio Project for project 3 
- Write a project proposal using R Markdown  ([guidelines](https://pressbooks.bccampus.ca/technicalwriting/chapter/7-1/)) 
- Describe the specific type of data, analysis, and results you expect to produce for the week 6 progress report
- Describe the specific type of data, analysis, and results you expect to produce for the week 10 final report 
- Save any reference articles (typically PDFs) in the project `resources` directory 
- Stage, commit, and push your work to the repo 

As your collaborator, I can clone the project to my local machine, make comments directly in your files, and push to GitHub. You can then pull from GitHub, and open the files or knit them to see my comments. 





---

[main page](../README.md)




