---
output: github_document
bibliography: "../resources/bib-etc/references-rr.bib"
csl: "../resources/styles/apa.csl"
link-citations: yes
--- 


# notes on document design 

Useful things to know about punctuation, headings, typography, and so forth.  


## hyphens and dashes

Adapted from *The Punctuation Guide* [@penn2018]. 

- `-` hyphen for compound words such as "advanced-level" or "first-year" or for numbers that are not inclusive such as phone numbers 1-812-555-8900. 
- `--` n-dash (the width of the letter N) means "through", e.g., July 9--August 17 or pages 37--59. These values designate an inclusive span. 
- `---`m-dash (the width of the letter M) is a punctuation mark that can be used to replace commas, parentheses, or a colon, but the em-dash is more emphatic. 

Examples of the em-dash include, 

> And yet, when the car was finally delivered---nearly three months after it was ordered---she decided she no longer wanted it, leaving the dealer with an oddly equipped car that would be difficult to sell. 

> Upon discovering the errors---all 124 of them---the publisher immediately recalled the books.

> The white sand, the warm water, the sparkling sun---this is what brought them to Hawaii.

## headings and typography 

This section based on the recommendations posted by Baker [-@baker2001] and Tufte [-@tufte2018].

- Other than the title, plan on having two levels of headings only
- Accent text can be a third level if needed. 
- Headings and subheadings can be a sans-serif typeface  
- The main body of text should be a serif typeface  (which I can't figure out how to do with a `github_document` output in R Markdown). 

## references


