---
output: github_document
--- 

# project 3


```{r 017-01, include = FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = TRUE)
options(echo = FALSE) # turns off echo in the console
```

ME 597 students only 

## getting started

- Project 3 is the extra work you do in addition to the regular class work to satisfy the requirements of a 500-level course  
- Your reproducibility project should contribute to your thesis work  
- The work should include data, analysis, graphical results 
- Replication of prior work relevant to your thesis is often an appropriate goal 


## milestones 

- By the end of week 1, you and I will have agreed upon a basic framework of the project 
- By week 6, you will have made substantial progress on your project 
- Students who have not met expectations by week 6 will be switched from ME 597 to ME 497 
- By week 10, project 3 is complete and meets the expectations we have set 

## assignment 

- By the end of week 0: Meet with me outside of class to discuss your proposed project 
- By the end of week 1: Submit a written draft proposal outlining the expected data, analysis, and results for the week 6 progress report and for week 10 final report. This is a draft subject to change, but we need to start thinking about this now. 



---

[main page](../README.md)




